spring.application.name=clinic
spring.datasource.url=jdbc:mysql://localhost:3306/clinic
spring.datasource.username=root
spring.datasource.password=umar@2004

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
